Use egrep wrapper

diff --git a/libexec/init b/libexec/init
--- a/libexec/init
+++ b/libexec/init
@@ -20,3 +20,17 @@ export HSENV_PV_COMMAND=cat
 if has_command pv; then
   export HSENV_PV_COMMAND=pv
 fi
+
+if echo "foo" | grep -E "^foo?$" > /dev/null 2> /dev/null; then
+  HSENV_EGREP_COMMAND=grep
+  HSENV_EGREP_OPTION=-E
+elif has_command egrep; then
+  HSENV_EGREP_COMMAND=egrep
+else
+  echo "error: \`grep -E\' or \`egrep\' required"
+  exit 1
+fi
+
+EGREP() {
+  $HSENV_EGREP_COMMAND $HSENV_EGREP_OPTION "$@"
+}
