Perform command selection only once

diff --git a/libexec/option b/libexec/option
--- a/libexec/option
+++ b/libexec/option
@@ -97,38 +97,44 @@ has_command() (
   which $1 > /dev/null 2> /dev/null
 )
 
-export HSENV_PV=cat
-if has_command pv; then
-  HSENV_PV_AND_CLEANUP() (
-    pv 2>&$HSENV_RAW_STDERR
-    pv_result=$?
-    if [ -t $HSENV_RAW_STDERR ]; then
-      $HSENV_NAWK 'BEGIN { printf("%c[F%c[K", 27, 27) }' >&$HSENV_RAW_STDERR
-    fi
-    return $pv_result
-  )
-  export HSENV_PV=HSENV_PV_AND_CLEANUP
+if [ -z "$HSENV_PV" ]; then
+  export HSENV_PV=cat
+  if has_command pv; then
+    HSENV_PV_AND_CLEANUP() (
+      pv 2>&$HSENV_RAW_STDERR
+      pv_result=$?
+      if [ -t $HSENV_RAW_STDERR ]; then
+        $HSENV_NAWK 'BEGIN { printf("%c[F%c[K", 27, 27) }' >&$HSENV_RAW_STDERR
+      fi
+      return $pv_result
+    )
+    export HSENV_PV=HSENV_PV_AND_CLEANUP
+  fi
 fi
 
-if echo "foo" | grep -E "^foo?$" > /dev/null 2> /dev/null; then
-  HSENV_GREP_E() (
-    grep -E "$@"
-  )
-  export HSENV_EGREP=HSENV_GREP_E
-elif has_command egrep; then
-  export HSENV_EGREP=egrep
-else
-  echo "error: \`grep -E' or \`egrep' required"
-  exit 1
+if [ -z "$HSENV_EGREP" ]; then
+  if echo "foo" | grep -E "^foo?$" > /dev/null 2> /dev/null; then
+    HSENV_GREP_E() (
+      grep -E "$@"
+    )
+    export HSENV_EGREP=HSENV_GREP_E
+  elif has_command egrep; then
+    export HSENV_EGREP=egrep
+  else
+    echo "error: \`grep -E' or \`egrep' required"
+    exit 1
+  fi
 fi
 
-if awk 'BEGIN{sub(/foo/, "")}' 2> /dev/null; then
-  export HSENV_NAWK=awk
-elif has_command nawk; then
-  export HSENV_NAWK=nawk
-else
-  echo "error: \`nawk' required"
-  exit 1
+if [ -z "$HSENV_NAWK" ]; then
+  if awk 'BEGIN{sub(/foo/, "")}' 2> /dev/null; then
+    export HSENV_NAWK=awk
+  elif has_command nawk; then
+    export HSENV_NAWK=nawk
+  else
+    echo "error: \`nawk' required"
+    exit 1
+  fi
 fi
 
 is_gnu_make() (
@@ -145,7 +151,9 @@ if [ -z "$HSENV_MAKE" ]; then
   fi
 fi
 
-export HSENV_TAR=tar
-if has_command gtar; then
-  export HSENV_TAR=gtar
+if [ -z "$HSENV_TAR" ]; then
+  export HSENV_TAR=tar
+  if has_command gtar; then
+    export HSENV_TAR=gtar
+  fi
 fi
