Move command selection code to libexec/option

diff --git a/libexec/option b/libexec/option
--- a/libexec/option
+++ b/libexec/option
@@ -86,3 +86,43 @@ installation_of() (
     echo install_local
   fi
 )
+
+has_command() (
+  which $1 > /dev/null 2> /dev/null
+)
+
+export PV=cat
+if has_command pv; then
+  export PV=pv
+fi
+
+if echo "foo" | grep -E "^foo?$" > /dev/null 2> /dev/null; then
+  HSENV_GREP_E() (
+    grep -E "$@"
+  )
+  export EGREP=HSENV_GREP_E
+elif has_command egrep; then
+  export EGREP=egrep
+else
+  echo "error: \`grep -E' or \`egrep' required"
+  exit 1
+fi
+
+if awk 'BEGIN{sub(/foo/, "")}' 2> /dev/null; then
+  export NAWK=awk
+elif has_command nawk; then
+  export NAWK=nawk
+else
+  echo "error: \`nawk' required"
+  exit 1
+fi
+
+export MAKE=make
+if has_command gmake; then
+  export MAKE=gmake
+fi
+
+export TAR=tar
+if has_command gtar; then
+  export TAR=gtar
+fi
